# Generated by Django 5.2.14 on 2026-05-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocolos', '0002_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alergias', models.TextField()),
                ('doencas_cronicas', models.TextField()),
                ('cirurgias_anteriores', models.TextField()),
                ('medicamentos_uso_continuo', models.TextField()),
                ('nome_mae', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(max_length=100)),
                ('queixa_principal', models.CharField(max_length=200)),
                ('historico_de_doenca_atual', models.TextField()),
                ('frequencia_respiratoria', models.CharField(max_length=50)),
                ('pressao_arterial', models.CharField(max_length=50)),
                ('frequencia_cardiaca', models.CharField(max_length=50)),
                ('temperatura', models.CharField(max_length=50)),
                ('saturacao', models.CharField(max_length=50)),
                ('ausculta_pulmonar', models.CharField(max_length=50)),
                ('estado_geral', models.CharField(max_length=50)),
                ('exames_solicitados', models.CharField(max_length=100)),
                ('diagnostico_provisorio', models.CharField(max_length=100)),
                ('conduta_tratamento', models.TextField()),
                ('medicamentos', models.ManyToManyField(blank=True, to='protocolos.medicamento')),
            ],
        ),
    ]
