# Generated by Django 5.2.14 on 2026-05-21 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('protocolos', '0003_rename_dosagem_maxima_medicamento_dosagens_maxima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ausculta_pulmonar',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cirurgias_anteriores',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='conduta_tratamento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='diagnostico_provisorio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='doencas_cronicas',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='estado_geral',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='exames_solicitados',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='frequencia_cardiaca',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='frequencia_respiratoria',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='historico_de_doenca_atual',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicamentos_uso_continuo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='pressao_arterial',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='queixa_principal',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='saturacao',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='temperatura',
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('alergias', models.TextField()),
                ('doencas_cronicas', models.TextField()),
                ('cirurgias_anteriores', models.TextField()),
                ('medicamentos_uso_continuo', models.TextField()),
                ('queixa_principal', models.CharField(max_length=200)),
                ('historico_de_doenca_atual', models.TextField()),
                ('frequencia_respiratoria', models.CharField(max_length=50)),
                ('pressao_arterial', models.CharField(max_length=50)),
                ('frequencia_cardiaca', models.CharField(max_length=50)),
                ('temperatura', models.CharField(max_length=50)),
                ('saturacao', models.CharField(max_length=50)),
                ('ausculta_pulmonar', models.CharField(max_length=50)),
                ('estado_geral', models.CharField(max_length=50)),
                ('exames_solicitados', models.CharField(max_length=100)),
                ('diagnostico_provisorio', models.CharField(max_length=100)),
                ('conduta_tratamento', models.TextField()),
                ('medicamentos', models.ManyToManyField(blank=True, to='protocolos.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paciente')),
            ],
        ),
    ]
