# Generated by Django 5.2.14 on 2026-05-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_paciente_alergias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ultimo_acesso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
