# Generated by Django 5.2.14 on 2026-05-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_consulta_conduta_tratamento_alter_consulta_id_and_more'),
        ('protocolos', '0005_alter_categoria_id_alter_medicamento_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='protocolos_utilizados',
            field=models.ManyToManyField(blank=True, to='protocolos.protocolo'),
        ),
    ]
