# Generated by Django 5.2.14 on 2026-05-29 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_consulta_protocolos_utilizados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('crm', models.CharField(blank=True, max_length=20)),
                ('especialidade', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PacienteExportado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exportacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da exportação')),
                ('exportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Exportado por')),
                ('medico_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_recebidos', to='dashboard.medico', verbose_name='Médico destino')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportacoes', to='dashboard.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Paciente Exportado',
                'verbose_name_plural': 'Pacientes Exportados',
                'ordering': ['-data_exportacao'],
            },
        ),
    ]
