# Generated by Django 6.0.5 on 2026-06-09 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_conduta_id_alter_consulta_id_alter_medico_id_and_more'),
        ('dashboard', '0010_prescricao'),
    ]

    operations = [
    ]
