# Generated by Django 5.2.14 on 2026-05-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dosagem_minima', models.DecimalField(decimal_places=3, max_digits=5)),
                ('dosagem_maxima', models.DecimalField(decimal_places=3, max_digits=6)),
                ('unidade_dosagem', models.CharField(max_length=50)),
            ],
        ),
    ]
