# Generated by Django 6.0.5 on 2026-05-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_farmaco', models.CharField(max_length=50)),
                ('tipo_farmaco', models.CharField(default='Geral', max_length=50)),
                ('dosagens_minima', models.DecimalField(decimal_places=3, max_digits=5)),
                ('dosagens_maxima', models.DecimalField(decimal_places=3, max_digits=6)),
                ('unidades_dosagem', models.CharField(max_length=50)),
                ('efeito_farmaco', models.TextField(blank=True, help_text='Efeito e indicacao clinica')),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sintoma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
