# Generated by Django 5.2.14 on 2026-05-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0002_medicamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='dosagem_maxima',
            new_name='dosagens_maxima',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='dosagem_minima',
            new_name='dosagens_minima',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='nome',
            new_name='nome_farmaco',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='unidade_dosagem',
            new_name='unidades_dosagem',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='efeito_farmaco',
            field=models.TextField(blank=True, help_text='Efeito e indicacao clinica'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tipo_farmaco',
            field=models.CharField(default='Geral', max_length=50),
        ),
    ]
