# Generated by Django 5.2.14 on 2026-05-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0002_medicamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='dosagem_maxima',
            new_name='dosagens_maxima',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='dosagem_minima',
            new_name='dosagens_minima',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='nome',
            new_name='nomes',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='unidade_dosagem',
            new_name='unidades_dosagem',
        ),
    ]
