# Generated by Django 5.2.14 on 2026-05-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0003_rename_dosagem_maxima_medicamento_dosagens_maxima_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='nomes',
            new_name='nome_farmaco',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='efeito_farmaco',
            field=models.TextField(blank=True, help_text='Efeito e indicacao clinica'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tipo_farmaco',
            field=models.CharField(default='Geral', max_length=50),
        ),
    ]
