# Generated by Django 6.0.5 on 2026-05-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0003_rename_dosagem_maxima_medicamento_dosagens_maxima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='nomes',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='efeito_farmaco',
            field=models.TextField(blank=True, help_text='Efeito e indicacao clinica'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='nome_farmaco',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tipo_farmaco',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sintoma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
